export const TOGGLE_THEATRE_MODE = 'TOGGLE_THEATRE_MODE';
export const TOGGLE_FREEZING_PLAYER_POSITION = 'TOGGLE_FREEZING_PLAYER_POSITION'
export const TOGGLE_CONTRIB_GUARD_VISIBILITY = 'TOGGLE_CONTRIB_GUARD_VISIBILITY';
export const TOGGLE_LIKES_ANIM_VISIBILITY = 'TOGGLE_LIKES_ANIM_VISIBILITY';
export const LIKES_CLICKER = 'LIKES_CLICKER';
export const CHEST_CLICKER = 'CHEST_CLICKER';
export const TOGGLE_COMMENTS_HIGHLIGHT = 'TOGGLE_COMMENTS_HIGHLIGHT';
export const TOGGLE_CHAT_LIMITS = 'TOGGLE_CHAT_LIMITS';
