export const TOGGLE_THEATRE_MODE = 'TOGGLE_THEATRE_MODE';
export const TOGGLE_FREEZING_PLAYER_POSITION = 'TOGGLE_FREEZING_PLAYER_POSITION'
export const TOGGLE_CONTRIB_GUARD_VISIBILITY = 'TOGGLE_CONTRIB_GUARD_VISIBILITY';
export const TOGGLE_LIKE_ANIM_VISIBILITY = 'TOGGLE_LIKE_ANIM_VISIBILITY';
export const LIKE_CLICKER = 'LIKE_CLICKER';
export const CHEST_CLICKER = 'CHEST_CLICKER';
export const TOGGLE_COMMENTS_HIGHLIGHT = 'TOGGLE_COMMENTS_HIGHLIGHT';
export const TOGGLE_CHAT_LIMITS = 'TOGGLE_CHAT_LIMITS';
